services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_web
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: celery_worker
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
